import { IsString, IsArray, IsOptional, IsBoolean, IsIn } from 'class-validator';
import { ApiProperty, ApiPropertyOptional } from '@nestjs/swagger';

export class CreateReportDto {
  @ApiProperty({ description: 'Client company number' })
  @IsString()
  clientId: string;

  @ApiProperty({ description: 'Report title' })
  @IsString()
  title: string;

  @ApiProperty({ description: 'Report format', enum: ['PDF', 'HTML'] })
  @IsIn(['PDF', 'HTML'])
  format: 'PDF' | 'HTML';

  @ApiPropertyOptional({ description: 'Tax calculation IDs to include', type: [String] })
  @IsOptional()
  @IsArray()
  @IsString({ each: true })
  calculationIds?: string[];

  @ApiPropertyOptional({ description: 'Template ID to use' })
  @IsOptional()
  @IsString()
  templateId?: string;

  @ApiPropertyOptional({ description: 'Include M branding', default: true })
  @IsOptional()
  @IsBoolean()
  includeBranding?: boolean;

  @ApiPropertyOptional({ description: 'Include charts and graphs', default: true })
  @IsOptional()
  @IsBoolean()
  includeCharts?: boolean;
}

export class ReportResponseDto {
  @ApiProperty({ description: 'Report ID' })
  id: string;

  @ApiProperty({ description: 'Client ID' })
  clientId: string;

  @ApiProperty({ description: 'Report title' })
  title: string;

  @ApiProperty({ description: 'Report format' })
  format: 'PDF' | 'HTML';

  @ApiProperty({ description: 'File path' })
  filePath?: string;

  @ApiProperty({ description: 'Generation timestamp' })
  generatedAt: Date;

  @ApiProperty({ description: 'Generated by user' })
  generatedBy: string;

  @ApiProperty({ description: 'Report content metadata' })
  content: any;
}
